config/routes.rb
Rails.application.routes.draw do
  
  default_url_options :host => "localhost:3000"
  
  resources :categories 
  resources :products
  

  resources :selected_products

  resources :orders do
  resources :order_items
  end

  
  get 'products_sync' => "products#products_sync"

  devise_for :users,:controllers => { :registrations =>'registration'}

  root :to =>'products#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :products
	validates :name, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :order_items, dependent: :destroy
	validates :user_id, presence: true
	#validates :total_cost, presence: true,
                  #  numericality: { :greater_than => 0 }
                    
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  validates :product_id, presence: true
  
  validates :price, presence: true
  									
  validates :quantity, presence: true,
                    numericality: { only_integer: true, :greater_than => 0 }
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories

  validates :name, presence: true,
                    length: { minimum: 2 }
 	
 	validates :description, presence: true,
                    length: { minimum: 5 }

  validates :price, presence: true,
  									numericality: { :greater_than => 0 }

  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/

                      
end

app/models/selected_product.rb
class SelectedProduct < ActiveRecord::Base

	belongs_to :product
	
	validates :product_id, presence: true

  validates :price, presence: true

	validates :quantity, presence: true,
                    numericality: { only_integer: true }



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true

  validates :age, presence: true,
  								numericality: { :greater_than => 0 }

  validates :mobile, presence: true,
                    length: { :minimum => 10, :maximum => 10 }

  validates :address, presence: true,
                    length: {  minimum: 5 }

  validates :country, presence: true

  validates :postal_code, presence: true
                
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	def index
    @category = Category.all
  end

	def show
    @category = Category.find(params[:id])
  end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
 
	  if @category.save
	    redirect_to @category
	  else
	    render 'new'
	  end
	end

	def update
	  @category = Category.find(params[:id])
	 
	  if @category.update(category_params)
	    redirect_to @category
	  else
	    render 'edit'
	  end
	end



	def destroy
	  @category = Category.find(params[:id])
	  @category.destroy
	 
	  redirect_to categories_path
	end


	private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

	def index
		
		@order_item = OrderItem.all

		
	end

	def create
		
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


	def index
		@order = Order.all

	end

	def new
		@order = Order.new
	end

	def create
		@order = Order.new
 		@order.user_id = current_user.id

 		if @order.save
	    
	    SelectedProduct.all.each do |product|

	 			if product.user_id == current_user.id

	 				@order_item = @order.order_items.create({ :product_id => product.product_id, :price => product.price, :quantity => product.quantity })
	 				
	 				product.delete

	 			end

 			end

 			

	    #redirecting to list of order items
	  	#redirect_to order_order_items_path(@order.id) 
	  	redirect_to orders_path(@order.id)	
 		
 		else
	    render 'new'
		end
 		
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def products_sync
    
  

          render :action => "index",:id=>params[:categories].to_i


       
  end 
 
  def index
    @product = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

	def create
    @product = Product.new(product_params)

    params[:product][:categories].delete_at(0)
    
    @product.categories << Category.find(params[:product][:categories].map(&:to_i))

    if @product.save
      redirect_to @product
    else
      render 'new'
    end

  end
 
 def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    
    params[:product][:categories].delete_at(0)
    @product.categories << Category.find(params[:product][:categories].map(&:to_i))

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
 
  redirect_to products_path
  end
 
  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :img)
    end

end

app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController

	def new

	@user= User.new

	end

	def create

		@user = User.new(user_params)

		@user.valid?
		
		if @user.errors.blank?

			@user.save

			redirect_to "/"
		else
			render :action => "new"
		end
	end

	protected
	  def after_inactive_sign_up_path_for(resource)
	        '/sign_up/inactive'
	  end

	private

		def user_params
	      params.require(:user).permit(:username, :age, :mobile, :country, :address, :postal_code, :email, :password, :password_confirmation)
	     
	 	 end
	end

app/controllers/selected_products_controller.rb
class SelectedProductsController < ApplicationController

	helper_method :current_user

	def index
    @product = SelectedProduct.all
  end


	def new
		
		@selected_product = SelectedProduct.new
	
	end

	def create
		@user = current_user
		@p = Product.find(params[:format])
		@selected_product = SelectedProduct.new
		#@product = params[:product]
		
		@selected_product.product_id = @p.id
		@selected_product.price = @p.price
		@selected_product.user_id = current_user.id
		@selected_product.quantity = 1
		
 		
	  if @selected_product.save
	  render  'index'
	  else
	    render 'new'
	  end
	end

	def edit

	end

	def update
		@selected_product = SelectedProduct.find(params[:id])
	 
	  if @selected_product.update(params.require(:selected_product).permit(:quantity))
	    render 'index'
	  else
	    render 'edit'
	  end
	end 

	def destroy
	  
	  @selected_product = SelectedProduct.find(params[:id])
	  
	  @selected_product.destroy
	 
		render  'index'
	end
		
	private
  def selected_product_params
    params.require(:p).permit(:quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/selected_products_helper.rb
module SelectedProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
 
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
 
<%=form_for(@category = Category.find(params[:id])) do |f| %>
 
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

 
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%if Category.all.count != 0%>
<h1>Categories</h1>
<!--<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3" align="centre">Links</th>
    </tr>
  </thead>
 <tbody>-->
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th colspan="3" align="centre">Links</th>
    </tr>
  </thead>
  <tbody>
  <% Category.all.each do |category| %>
    
    <tr>
      <td><%= category.name %></td>
      
      <td><%= link_to 'Show', category_path(category) %>&nbsp &nbsp |
      <%= link_to 'Edit', edit_category_path(category) %>&nbsp &nbsp |
      <%= link_to 'Destroy', category_path(category),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      
    </tr>
  
  <% end %>
  </tbody>
</table>
<td><%= link_to 'Add Category', new_category_path %></td>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

  
   <%= form_for @category do |f| %>
 
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

 
<%= link_to 'All Categories', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
 




<%= link_to 'Edit', edit_category_path(@category) %>  |

<%= link_to 'List Of categories', categories_path %> 

app/views/home/dashboard.html.erb
<%= link_to "Sign out", destroy_member_session_path, :method => :delete %>

app/views/home/index.html.erb
<% if user_signed_in? %>

<h3>you have succesfully signed in</h3>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

<% else %>

<h1> welcom to rails community</h1>
<%= link_to "Sign In", new_user_session_path, :method => :get %>
<%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>

app/views/order_items/index.html.erb
<%if OrderItem.all.count != 0%>
<h1>OrderItems</h1>
<table class="table">
  <thead>
    <tr>
      <th>Order Id</th>
      <th>Product Name</th>
      <th>Product Image</th>
      <th>Price</th>
      <th>Quantity</th>
      
    </tr>
  </thead>
 <tbody>
  <% @total_cost = 0 %>
  <% @order_item.each do |order| %>
    
    <%if order.order_id == params[:order_id].to_i%>
      <% @product = Product.find(order.product_id)%>
      <tr>
        <td><%=order.order_id %></td>
        <td><%=@product.name %></td>
        <td><%= image_tag @product.img.url %></td>
        <td><%=order.price %></td>
        <td><%=order.quantity %></td>
      </tr>
    <% end %>
    
  <% end %>
<tbody>
</table>

<% end %>

app/views/orders/index.html.erb
<% Order.all.each do |user_order|%>
  <% if user_order.user_id == current_user.id %>
    <% @total_cost = 0 %>
    <% @id = user_order.id%>
    <% OrderItem.all.each do |order_item| %>
        
        <%if order_item.order_id == user_order.id%>
          <% @total_cost += (order_item.price*order_item.quantity) %>
        <% end %>
    <% end %>

    <table class="table">
  <thead align="center">
    <tr>
      <th colspan="5">Order</td>
    </tr>
    <tr>
      <th>Order Id</th>
      <th>Total Cost</th>
      <th>Status</th>
      <th>Date of Order</th>
      <th>Links</th>
      
      
    </tr>
  </thead>
 <tbody>
  
      <tr>
        <td><%=user_order.id %></td>
        <td><%=@total_cost %></td>
        <td><%=user_order.status %></td>
        <td><%=user_order.created_at %></td>
        <td><%= link_to 'Order Items',order_order_items_path(@id)%></td>
      </tr>
    <% end %>
  <% end %>
<tbody>
</table>

app/views/orders/new.html.erb
<h1>Order Saved</h1>

app/views/products/_comment.html.erb
<table>
<tr>
  <th>Product Name</th>
  <th>Description</th>
  <th>Price</th>
<tr>

<tr><td><%= product.name %></td></tr>
<tr><td><%= product.description %></td></tr>
<tr><td><%= product.price %></td></tr>
</table>
 
<p>
  <%= link_to 'Remove Product', [product.category, product],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/products/_form.html.erb
<%= form_for(@product, html: {:multipart => true  }) do |f| %>
  
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
  <p>
    <%= f.label :img %><br>
    <%= f.file_field :img %>
  </p>
 
  <p>
    <%= f.label :category %><br>
    <%=f.select :categories, options_for_select(Category.all.collect {|c| [c.name, c.id] } ), {}, :multiple => true%>

  </p>
  </p>
  <p>
  
    <%= f.submit %>
  </p>
<% end %>

app/views/products/_list.html.erb
<h1>Products After Sync</h1>

app/views/products/_product.html.erb
<table border="1">
<tr>
  <th>Product Name</th>
  <th>Description</th>
  <th>Price</th>
<tr>

<tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
</tr>
</table>
 
<p>
  <%= link_to 'Remove Product', [product.category, product],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

  <%= link_to 'Add to Cart', new_selected_product_path %>
</p>

app/views/products/_products_sync.html.erb
<%=form_tag(products_sync_path, :method => 'get')%>
  <% @category = Category.all %>

  <%= select_tag "categories", options_from_collection_for_select(@category, "id", "name",params[:categories]),{:include_blank => 'All'}%>

<%= submit_tag nil, :class => "form_submit"%>

 

app/views/products/edit.html.erb
<h1>Edit Product</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render 'products/products_sync' %> 

<% if params[:categories] != nil %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Image</th>
        <th>Price</th>
        <th colspan="3" align="centre">Links</th>
      </tr>
    </thead>
   <tbody>
    <% @flag_sync = false %>
    <% Product.all.each do |product|%>
      
      <% if product.categories.count != 0 %>

        
      
        <% product.categories.each do |category| %>
         
          <% if  category.id == params[:categories].to_i %>
            <% @flag_sync = true %>  
            <tr>
              <td><%= product.name %></td>
              <td><%= product.description %></td>
              <td><%= image_tag product.img.url %></td>
              <td><%= product.price %></td>
              <td><%= link_to 'Show', product_path(product) %>&nbsp &nbsp 
              <% if user_signed_in? %>
                <% if current_user.is_admin == true %>
                <%= link_to 'Edit', edit_product_path(product) %>&nbsp &nbsp
                <%= link_to 'Destroy', product_path(product),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              <% end %>
            </tr>

          <% end %>
        
        <%  end %>
      
      <%  end %>

    <% end %>
    <% if @flag_sync == false %>
        <script type="text/javascript">
          window.location.href="/"  // put your correct path in a string here
        </script>
    <% end %>
    </tbody>
  </table>


<% end %>




<%if Product.all.count != 0 && params[:categories] == nil%>
  <h1>Products</h1>
  <% if user_signed_in? %>
      <% if current_user.is_admin == true %>
        <div  align="right" style="font-size:125%">
          <%= link_to 'Add Product', new_product_path %> &nbsp &nbsp | &nbsp &nbsp 
          <%= link_to 'Add Category', new_category_path %>&nbsp &nbsp | &nbsp &nbsp 
          <%= link_to 'List Categories', categories_path %>
        </div>
      <% end %>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Image</th>
        <th>Price</th>
        <th colspan="3" align="centre">Links</th>
      </tr>
    </thead>
   <tbody>
    <% Product.all.each do |product| %>
      
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= image_tag product.img.url %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product_path(product) %>&nbsp &nbsp 
        <% if user_signed_in? %>
          <% if current_user.is_admin == true %>
          <%= link_to 'Edit', edit_product_path(product) %>&nbsp &nbsp
          <%= link_to 'Destroy', product_path(product),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    
    <% end %>
  <tbody>
  </table>

  <% end %>

app/views/products/list.html.erb
<h1>Products After Sync</h1>

app/views/products/new.html.erb
<h1>New Product</h1>

  <% if user_signed_in? %> 
    <%= render 'products/form' %>
  <% end %>
<%= link_to 'List Of Articles', products_path %>

app/views/products/products_sync.html.erb
<%=form_tag(products_sync_path, :method => 'get')%>
  <% @category = Category.all %>

  <%= select_tag "categories", options_from_collection_for_select(@category, "id", "name",params[:categories]),{:include_blank => 'All'}%>

<%= submit_tag nil, :class => "form_submit"%>

 

app/views/products/show.html.erb
<% if user_signed_in? %>
  <% if current_user.is_admin == true %>
  <%= link_to 'Edit', edit_product_path(@product) %>  |
  <%= link_to 'Destroy', product_path(@product),
                method: :delete,
                data: { confirm: 'Are you sure?' } %> |
  <% else %>
  <%= link_to 'Add to cart', selected_products_path(@product),
                method: :post,
                data: { confirm: 'Are you sure?' }%>  |
  <% end %>
<% end %> 
  <%= link_to 'List Of products', products_path %>  


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Price</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
     
    <tr>
      <td><%=@product.name %></td>
      <td><%=@product.description %></td>
      <td><%=image_tag @product.img.url %></td>
      <td><%=@product.price %></td>
      <td><% @product.categories.each do |c| %>
          <%= c.name %><br/><% end %>
      </td>
      
    </tr>
  
  <tbody>
</table>

app/views/selected_products/index.html.erb
<%if SelectedProduct.all.count != 0%>
<div>
  <h1>Cart</h1>
  <h4 style="float:right !important"><%= link_to 'Place an order', orders_path,
                method: :post,
                data: { confirm: 'Are you sure?' } %></h4>
<div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3" align="centre">Links</th>
    </tr>
  </thead>
 <tbody>
  <% SelectedProduct.all.each do |product| %>
  <% if product.user_id == current_user.id %>
    <% s = Product.find(product.product_id)%>
      <tr>
        <td><%= s.name %></td>
        <td><%= s.description %></td>
        <td><%= image_tag s.img.url %></td>
        <td><%= s.price %></td>
        
        <td>
            <%= form_for :selected_product, :url => selected_product_path(id: product), method: :put do |f| %>
                <div class="field">
                    <%= f.number_field :quantity, :value => product.quantity %>
                    <%= submit_tag "Update" %>
                </div>
            <% end %>

        </td>
        
        <% if user_signed_in? %>
          <td>
          <%= link_to 'Edit', edit_selected_product_path(product) %>&nbsp &nbsp
          <%= link_to 'Remove', selected_product_path(product),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
          
        <% end %>
      </tr>
    <% end %>
  <% end %>
<tbody>
</table>

<% end %>
<%= link_to 'New Product', new_product_path %> &nbsp &nbsp | &nbsp &nbsp 
<%= link_to 'New Category', new_category_path %>

app/views/selected_products/new.html.erb
  <p>
  <strong>Name:</strong>
    <%=@p.name %>
  </p>
  
  <p>
    <strong>Description:</strong>
    <%=@p.description %>
  </p>
  
  <p>
    <strong>Price:</strong>
    <%= @p.price %>
  </p>
 
  <p>
    <strong>Image:</strong>
    <%= image_tag @p.img.url %>
  </p>
  
  <p>
  <%= form_tag "/selected_products" do %>
  <%= text_field_tag "quantity" %>
  <%= submit_tag "Add" %>
  <% end %>
 </p>

  
<%= link_to 'List Of products', products_path %>  